# Generated by Django 5.1.5 on 2025-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0003_videotranscriptionanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
