# Generated by Django 5.1.5 on 2025-02-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0004_realtimetranscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimetranscription',
            name='abusive_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimetranscription',
            name='bad_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimetranscription',
            name='overall_sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='realtimetranscription',
            name='sentiment_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='abusive_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='bad_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='overall_sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='sentiment_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
