# Generated by Django 5.1.5 on 2025-02-09 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0006_alter_realtimetranscription_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='videotranscriptionanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='overall_sentiment',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='sentiment_score',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='overall_sentiment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='sentiment_score',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('abusive_words', models.TextField(blank=True, null=True)),
                ('bad_words', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('real_time_transcription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='videoprocessor.realtimetranscription')),
                ('video_transcription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='videoprocessor.videotranscriptionanalysis')),
                ('transcription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analysis', to='videoprocessor.transcription')),
            ],
        ),
    ]
