# Generated by Django 5.1.5 on 2025-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0007_transcription_videotranscriptionanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='real_time_transcription',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='video_transcription',
        ),
        migrations.RemoveField(
            model_name='videotranscriptionanalysis',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Transcription',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
