# Generated by Django 5.1.5 on 2025-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0008_remove_sentimentanalysis_real_time_transcription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
