# Generated by Django 5.1.5 on 2025-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0009_alter_videotranscriptionanalysis_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimetranscription',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='overall_sentiment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='realtimetranscription',
            name='sentiment_score',
            field=models.FloatField(),
        ),
    ]
