# Generated by Django 5.1.5 on 2025-02-16 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0010_realtimetranscription_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='overall_sentiment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='sentiment_score',
            field=models.FloatField(),
        ),
    ]
