# Generated by Django 5.1.5 on 2025-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0011_alter_videotranscriptionanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='overall_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
