# Generated by Django 5.1.5 on 2025-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessor', '0012_alter_videotranscriptionanalysis_overall_sentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscriptionanalysis',
            name='overall_sentiment',
            field=models.CharField(default='Neutral', max_length=50),
        ),
    ]
